### ISSUE TITLE
Powering off not working after updating plugin to v1.7.3

### ISSUE THREAD

**Issue by pellz0r** [ralmn/OctoPrint-Ikea-tradfri#49]
Updated the plugin to 1.7.3, and after that the power off button stopped working. Checked the logs that said:
`2021-11-04 20:49:27,061 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin ikea_tradfri
Traceback (most recent call last):
  File "/home/sebastian/OctoPrint/venv/lib/python3.9/site-packages/octoprint/server/api/__init__.py", line 158, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/sebastian/OctoPrint/venv/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1737, in wrapper
    return f(*args, **kwargs)
  File "/home/sebastian/OctoPrint/venv/lib/python3.9/site-packages/octoprint_ikea_tradfri/__init__.py", line 573, in on_api_command
    self.turnOff(data['dev'])
  File "/home/sebastian/OctoPrint/venv/lib/python3.9/site-packages/octoprint_ikea_tradfri/__init__.py", line 525, in turnOff
    if not f('connect_palette2' in device and device['connect_palette2']):
NameError: name 'f' is not defined`

I suspect a small typo on row 525 in __init__.py is the culprit.

https://github.com/ralmn/OctoPrint-Ikea-tradfri/blob/423a5179a175c905753cdbb1b28ad80fb4444c35/octoprint_ikea_tradfri/__init__.py#L525

**Comment by ralmn** [comment]
Fix in 1.7.5
